volumes:
  storage:


services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: app
    volumes:
      - storage:/var/www/html/storage/
    expose:
      - 8080

  horizon:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: horizon
    volumes:
      - storage:/var/www/html/storage/
    command: php artisan horizon
